### ISSUE TITLE
Exclude Sass and CSS built-in fuctions

### ISSUE THREAD

**Issue by aziz** [fChristenson/sassy-stats#14]
`format` is a CSS build-it function

Here's a list of built-in sass functions that should be excluded from @function report: 
http://www.sass-lang.com/documentation/Sass/Script/Functions.html

I'm interested in seeing the list of built-in Sass functions I'm using. Adding a separate section for those might be beneficial

**Comment by fChristenson** [comment]
fixed in 1.8.1

**Comment by fChristenson** [comment]
fixed in 1.8.2
