### ISSUE TITLE
Report Total Numbers

### ISSUE THREAD

**Issue by aziz** [fChristenson/sassy-stats#16]
- Total number of variables 
- Total number of mixins
- Total number of functions

- Total number of selectors
- Total number of files

**Comment by fChristenson** [comment]
Added in 1.6.0
* Total number of variables
* Total number of mixins
* Total number of functions

Added in 1.7.0
* Total number of files

Going one further on the selectors and going to list id, class etc as separate values with a total at the end, e.g

SELECTORS
-----------------------------------
id: 100
class: 500
tag: 10

**Comment by fChristenson** [comment]
selectors added in 1.8.0
